Repository knative-extensions/.github, pull requests merged in 2020-11, with the labels that each got.

#71 Show (-got,+want) stuff in the formatter
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#70 make Releasability report pretty
  workflow-templates/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#69 to support releases, adding a manual only release notes generator workflow
  workflow-templates/knative-release-notes.properties.json
  workflow-templates/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/L

#72 update releasability script to match the out of date logic of knobots
  workflow-templates/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/S

#73 Fix a bug in t.Xf() reporting
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#75 Add top level PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cla: yes, lgtm, size/M

#76 Update woke version to 0.4.1
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#77 Skip slack notification when SLACK_WEBHOOK not set.
  workflow-templates/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
