Repository knative-extensions/.github, pull requests merged in 2020-08, with the labels that each got.

#1 Add the stale workflow to the org repo
  .github/workflows/stale.yaml
Labels: approved, cla: yes, lgtm, size/M

#2 Fix the directory for the github action.
  workflow-templates/stale.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3 Add missing properties.json file
  workflow-templates/blender.svg
  workflow-templates/stale.properties.json
Labels: approved, cla: yes, lgtm, size/L

#4 Fix the image
  workflow-templates/blender.svg
Labels: approved, cla: yes, lgtm, size/L

#5 Drop trailing comma
  workflow-templates/stale.properties.json
Labels: approved, cla: yes, lgtm, size/XS

#6 Rename workflow to avoid collisions on page.
  workflow-templates/knative-stale.properties.json
  workflow-templates/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/XS

#7 Add the other base workflows from knative/pkg
  workflow-templates/knative-go-build.properties.json
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.properties.json
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-style.properties.json
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.properties.json
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#10 Fix stale job cron from every minute to everyday
  workflow-templates/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/XS

#9 add a README saying these are autogen and where they come from
  README.md
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-stale.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M
