Repository knative-extensions/.github, pull requests merged in 2020-12, with the labels that each got.

#79 Add main branch as a target for all actions
  workflow-templates/knative-boilerplate.yaml
  workflow-templates/knative-donotsubmit.yaml
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-security.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#80 Remove redundant format linter.
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#81 Use ko v0.6.0
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#82 Update releasability
  workflow-templates/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
