Repository knative-extensions/.github, pull requests merged in 2020-09, with the labels that each got.

#12 Switch all GitHub actions to use Go 1.14
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#13 Add golangci-lint action to the code style action.
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#14 Drop go vet from the actions, it's redundant with linting.
  workflow-templates/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#15 Add an action that warns about usages of divisive language.
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#16 use vet with tags - it will report build failures
  workflow-templates/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/S

#17 grep returns an exit code when there are no matches
  workflow-templates/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#18 Don't run actions on push, nobody checks those.
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-stale.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#19 Run woke checks only on PRs.
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#20 Enable codecov
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#21 Remove trailing slash
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#22 Add a DO NOT SUBMIT action.
  workflow-templates/knative-donotsubmit.properties.json
  workflow-templates/knative-donotsubmit.yaml
Labels: approved, cla: yes, lgtm, size/M

#23 Add a github.com/client9/misspell action
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#25 Several workflow adjustments
  workflow-templates/knative-donotsubmit.yaml
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#28 Add a check for trailing whitespace.
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#29 Add a step to flag missing newlines at EOF.
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#30 Add goimports checking
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#32 Fix default .wokeignore with *
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#31 Combine installations of reviewdog.
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#33 Fixup the finds to properly exclude vendor et al
  workflow-templates/knative-donotsubmit.yaml
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#36 Try again go 1.15
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#39 Codify the relationship between `knative-sandbox/.github` and `knative/.github`
  .github/workflows/check-source-of-truth.yaml
  .github/workflows/sync.yaml
  README.md
Labels: approved, cla: yes, lgtm, size/M

#35 Create an action for validating knative boilerplate headers.
  workflow-templates/knative-boilerplate.properties.json
  workflow-templates/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/L

#41 Fix issue with action detecting '.git' from '.github'
  .github/workflows/sync.yaml
Labels: approved, cla: yes, lgtm, size/XS

#42 Make update-codegen.sh optional
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#40 Add LICENSE file
  LICENSE
Labels: approved, cla: yes, lgtm, size/L

#43 Turn the output of auto formatting tools into error annotations.
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#45 Suggest not to format the traling formatting arugment if it's the only one
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#46 Cover the rare case of %T
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#47 Capture t.Logf in addition
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#48 Cover some edgecases I found while updating other repos
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#49 Run golangci-lint on the entire codebase, not just new lines
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS
