Repository knative-extensions/.github, pull requests merged in 2020-10, with the labels that each got.

#51 Make the script more precise and permit for more verbs and edge cases
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#52 Run Github's security checks against our Golang code
  workflow-templates/knative-security.properties.json
  workflow-templates/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/M

#53 do not use set-env or add-path
  workflow-templates/knative-boilerplate.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#54 do not lint .ai files.
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#55 Enable manual trigger of the github actions sync workflow
  .github/workflows/sync.yaml
Labels: approved, cla: yes, lgtm, size/XS

#56 adding Scott to owners
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#57 Security check on push on the main and release branches
  workflow-templates/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS

#58 Fix knative-security whitespace lint
  workflow-templates/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS

#62 Pin woke version again to avoid breaks from sneaking in
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#64 adding releasability action
  workflow-templates/knative-releasability.properties.json
  workflow-templates/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/L

#65 Redirect folks to the right knobots
  README.md
  workflow-templates/knative-boilerplate.yaml
  workflow-templates/knative-donotsubmit.yaml
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-security.yaml
  workflow-templates/knative-stale.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#66 bump releasability for 0.19
  workflow-templates/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#67 Bump golangci-lint version
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#68 Exclude wire gen files.
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S
