Repository knative-extensions/.github, pull requests merged in 2021-01, with the labels that each got.

#85 add a flag to test if webhook secrets are set.
  workflow-templates/knative-releasability.yaml
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#86 Add support for git attributes, keep legacy filters for now
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, kind/cleanup, kind/enhancement, lgtm, size/S

#89 Fix missing single quote in knative-style.yaml
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S
