Repository knative-extensions/.github, pull requests merged in 2021-12, with the labels that each got.

#154 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/XS

#155 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/XS

#156 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#157 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#160 Fix tools not being installed in knative-style
  workflow-templates/knative-style.yaml
Labels: approved, lgtm, size/XS, kind/bug
