Repository knative-extensions/.github, pull requests merged in 2021-11, with the labels that each got.

#148 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#147 Update the golangci-lint version to 1.43
  workflow-templates/knative-style.yaml
Labels: cla: yes, approved, lgtm, size/XS

#149 Change 'go get' to 'go install'
  workflow-templates/knative-boilerplate.yaml
  workflow-templates/knative-releasability.yaml
  workflow-templates/knative-release-notes.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: cla: yes, approved, lgtm, kind/cleanup, size/S

#150 Remove GOPATH from knative-verify
  workflow-templates/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/XS

#151 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/XS

#152 Bump releasability action to start asserting v1.1
  workflow-templates/knative-releasability.yaml
Labels: cla: yes, approved, lgtm, size/XS
