Repository knative-extensions/.github, pull requests merged in 2021-05, with the labels that each got.

#106 bump release to 0.23
  workflow-templates/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#105 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
Labels: cla: yes, lgtm

#103 Don't ignore go.mod for releasability
  workflow-templates/knative-releasability.yaml
Labels: approved, cla: yes, kind/bug, kind/cleanup, lgtm, size/S

#104 Bump Go version to release notes workflow
  workflow-templates/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/XS

#108 Bump to go 1.16
  workflow-templates/knative-boilerplate.yaml
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-releasability.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, size/S

#110 Fix indent for andstor/file-existence-action@v1
  workflow-templates/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#111 fix coverage
  workflow-templates/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#112 use exec echo to avoid running init and TestsMain when building
  workflow-templates/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#113 Revert "fix coverage"
  workflow-templates/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#114 Update woke to 0.8.0
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#115 Update golangci-lint to 1.40
  workflow-templates/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#116 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#117 Add mkdocs branch to templates to support docs migration
  workflow-templates/knative-boilerplate.yaml
  workflow-templates/knative-donotsubmit.yaml
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-security.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, size/S

#118 Bump releasability action to start asserting v0.24
  workflow-templates/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
