Repository knative-extensions/.github, pull requests merged in 2022-04, with the labels that each got.

#189 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#190 drop workflows templates
  README.md
  workflow-templates/blender.svg
  workflow-templates/knative-boilerplate.properties.json
  workflow-templates/knative-donotsubmit.properties.json
  workflow-templates/knative-go-build.properties.json
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.properties.json
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-releasability.properties.json
  workflow-templates/knative-releasability.yaml
  workflow-templates/knative-release-notes.properties.json
  workflow-templates/knative-release-notes.yaml
  workflow-templates/knative-security.properties.json
  workflow-templates/knative-security.yaml
  workflow-templates/knative-stale.properties.json
  workflow-templates/knative-stale.yaml
  workflow-templates/knative-style.properties.json
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.properties.json
  workflow-templates/knative-verify.yaml
Labels: approved, lgtm, size/L

#191 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#192 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#193 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#194 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
