Repository knative-extensions/.github, pull requests merged in 2022-03, with the labels that each got.

#182 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#183 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#184 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#186 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#185 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: approved, lgtm, size/XS

#187 Remove the matrix from some tests.
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, size/M, lgtm, kind/enhancement

#174 Refactor to reusable workflows
  workflow-templates/knative-boilerplate.yaml
  workflow-templates/knative-donotsubmit.yaml
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-releasability.yaml
  workflow-templates/knative-release-notes.yaml
  workflow-templates/knative-security.yaml
  workflow-templates/knative-stale.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, lgtm, size/XL

#188 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
