Repository knative-extensions/.github, pull requests merged in 2023-10, with the labels that each got.

#249 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#250 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#251 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#252 Add a default issue template and update default PR template
  .github/PULL_REQUEST_TEMPLATE.md
  ISSUE-TEMPLATE.md
Labels: approved, lgtm, size/XS
